# Site settings
title: Space Apps Lyon
edition:
  date: "20 au 21 octobre 2018"
  year: 2018
email: spaceappslyon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Space Apps, challenge d'innovation international de la NASA à Lyon, au Planétarium du 19 au 21 octobre 2018.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceappslyon.fr/" # the base hostname & protocol for your site
avatar: "/img/logos/Space-apps-apercu.jpg"
show-avatar: true

defaults:
   -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      comments: true
      bigimg:
        - "/img/pages/SLS-engine-section.jpg"
        - "/img/pages/alaskan-coast.jpg"
        - "/img/pages/nasa-01.jpg"
        - "/img/pages/omega-nebula.jpg"
        - "/img/pages/orion-parachutes.jpg"
        - "/img/pages/red-planet-hale-crater.jpg"
        - "/img/pages/spacex-dragon.jpg"
        - "/img/pages/super-hot-ground-test.jpg"

# User setting
social:
  twitter: spaceappslyon
  facebook: spaceappslyon
  github: spaceappslyon
  discourse: hub.spaceappslyon.com
  meetup: Space-Apps-Lyon

# Navabar for pages
navbar-links:
  Home: "http://spaceappslyon.fr"
  Informations:
    - Space Apps, c'est quoi ?: "space-apps-challenge-c-est-quoi"
    - Qui peut participer ?: "qui-peut-participer-a-space-apps"
    - Déroulement: "deroulement-space-apps-lyon-2018"
    - Challenges: "les-challenges-de-la-nasa-space-apps-2018"
    - Jury: "competition-jury-de-space-apps-lyon-2018"
    - Comment venir?: "venir-a-space-apps-lyon-au-planetarium"
  Inscriptions: "https://2018.spaceappschallenge.org/locations/lyon-france"

address:
  - line: "Planétarium"
  - line: "Place de la Nation, 69120 Vaulx-en-Velin"

# Build settings
markdown: kramdown

#build output dir
destination: _site

#exclude from build
exclude: ["bower.json",
          "Gemfile*",
          "package.json",
          "README.md",
          "LICENSE.md",
          "Gruntfile.js",
          "node_modules",
          "bower_components",
          "tests"]

#sass config
sass:
  sass_dir: _sass
  style: compressed
