# Site settings
title: Space Apps Lyon
edition:
  date: "22 au 24 avril 2016"
  year: 2016
email: spaceappslyon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Space Apps, challenge d'innovation de la NASA à Lyon, aux Subsistances du 22 au 24 avril 2016
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceappslyon.com/" # the base hostname & protocol for your site

# User setting
social:
  twitter: spaceappslyon
  facebook: spaceappslyon
  github: spaceappslyon
  discourse: hub.spaceappslyon.com
  meetup: Space-Apps-Lyon

address:
  - line: "Les Subsistances"
  - line: "8 bis Quai Saint-Vincent, 69001 Lyon"

# Build settings
markdown: kramdown

#build output dir
destination: _site

#exclude from build
exclude: ["bower.json",
          "Gemfile*",
          "package.json",
          "README.md",
          "LICENSE.md",
          "Gruntfile.js",
          "node_modules",
          "bower_components",
          "tests"]

#sass config
sass:
  sass_dir: _sass
  style: compressed
