# Site settings
title: Space Apps Lyon
edition:
  date: "20 au 21 octobre 2018"
  year: 2018
email: spaceappslyon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Space Apps, challenge d'innovation international de la NASA à Lyon, au Planétarium du 19 au 21 octobre 2018.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceappslyon.fr/" # the base hostname & protocol for your site
avatar: "/img/logos/spaceappslyon_black.png"
show-avatar: true

defaults:
   -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      comments: true
      bigimg:
        - "/img/pages/earth_rise.jpg"
        - "/img/pages/earth.jpg"
        - "/img/pages/europa.jpg"
        - "/img/pages/mars.jpg"
        - "/img/pages/space.jpg"
        - "/img/pages/shuttle.jpg"
        - "/img/pages/sombrero.jpg"
        - "/img/pages/growing.jpg"

# User setting
social:
  twitter: spaceappslyon
  facebook: spaceappslyon
  github: spaceappslyon
  discourse: hub.spaceappslyon.com
  meetup: Space-Apps-Lyon

# Navabar for pages
navbar-links:
  Home: "http://spaceappslyon.fr"
  Informations:
    - Space Apps, c'est quoi ?: "space-apps-challenge-c-est-quoi"
    - Qui peut participer ?: "qui-peut-participer-a-space-apps"
    - Déroulement: "deroulement-space-apps-lyon-2016"
    - Challenges: "les-challenges-de-la-nasa-space-apps-2016"
    - Jury: "competition-jury-de-space-apps-lyon-2016"
    - Comment venir?: "venir-a-space-apps-lyon-aux-subsistances"
  Inscriptions: "https://2016.spaceappschallenge.org/locations/lyon-france"

address:
  - line: "Planétarium"
  - line: "Place de la Nation, 69120 Vaulx-en-Velin"

# Build settings
markdown: kramdown

#build output dir
destination: _site

#exclude from build
exclude: ["bower.json",
          "Gemfile*",
          "package.json",
          "README.md",
          "LICENSE.md",
          "Gruntfile.js",
          "node_modules",
          "bower_components",
          "tests"]

#sass config
sass:
  sass_dir: _sass
  style: compressed
